"""I-7 — deterministic claim artifacts (Phase I finale, 2026-08-23).

Every artifact is a DRAFT document the user reviews, edits, and sends
themselves (spec §9.1: information and document preparation the consumer
performs themselves — never negotiation on their behalf). No LLM anywhere
in this module. Citations in letter bodies come ONLY from the P&C curated
set (agents.pc_citations).

Artifact catalog — spec §6, both batches:

  Batch A (early claim): claim_log, policy_request_letter, vacancy_notice,
      work_auth_rider, packout_demand, contents_inventory (CSV + PDF)
  Batch B (dispute): depreciation_challenge, supplement_cover,
      demand_letter, dfs_mediation_prefill, deadline_calendar (.ics)

User facts come from the claim's ``details`` jsonb (user-supplied only,
never inferred from documents). Missing facts render as bracketed
placeholders and are listed in ``missing_fields`` — the UI highlights them
rather than the generator inventing values.
"""

from __future__ import annotations

import csv
import html
import io
from datetime import date, datetime, timezone

_DRAFT_NOTE = (
    "This is a draft document prepared by the policyholder using LegalClear "
    "information tools. It is a starting point, not legal advice. Review it, "
    "correct it, and send it yourself."
)

_DETAIL_KEYS = (
    "insured_name", "insured_address", "insurer_name", "claim_number",
    "policy_number", "adjuster_name", "property_address",
    "fire_report_number", "mortgage_company", "phone_number",
)


def _fmt_date(raw: str | None, placeholder: str = "[date]") -> str:
    if not raw:
        return placeholder
    try:
        return date.fromisoformat(raw).strftime("%B %d, %Y")
    except ValueError:
        return raw


def _d(details: dict, key: str, placeholder: str) -> str:
    value = (details or {}).get(key)
    return html.escape(str(value)) if value else placeholder


def missing_fields(details: dict) -> list[str]:
    return [k for k in _DETAIL_KEYS if not (details or {}).get(k)]


# ────────────────────────────────────────────────────────────────────────
# Letter chrome (HTML)
# ────────────────────────────────────────────────────────────────────────

def _letter_html(body_html: str, details: dict, title: str) -> str:
    insured = _d(details, "insured_name", "[your name]")
    address = _d(details, "insured_address", "[your address]")
    today = datetime.now(timezone.utc).date().strftime("%B %d, %Y")
    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>{html.escape(title)}</title>
<style>
  body {{ font-family: Georgia, 'Times New Roman', serif; font-size: 12pt;
         line-height: 1.5; color: #111; margin: 2.5cm; }}
  .header {{ margin-bottom: 2em; }}
  .draft {{ border: 1px solid #999; background: #f4f4f4; padding: 8px 12px;
            font-family: Helvetica, Arial, sans-serif; font-size: 9pt;
            color: #444; margin-bottom: 2em; }}
  .body p {{ margin: 0 0 1em; }}
  .sig {{ margin-top: 4em; }}
  .foot {{ margin-top: 3em; font-size: 9pt; color: #666; }}
</style></head>
<body>
<div class="draft">{_DRAFT_NOTE}</div>
<div class="header">
  {insured}<br>
  {address}<br><br>
  {today}
</div>
<div class="body">
{body_html}
</div>
<div class="sig">
  {insured}<br>
  <span style="font-size:10pt;color:#555">{_d(details, "phone_number", "")}</span>
</div>
<div class="foot">Generated by LegalClear on {today}. {_DRAFT_NOTE}</div>
</body></html>"""


def _render_pdf(html_str: str) -> bytes:
    from weasyprint import HTML  # heavy import — lazy
    return HTML(string=html_str).write_pdf()


# ────────────────────────────────────────────────────────────────────────
# Artifact builders
# ────────────────────────────────────────────────────────────────────────

def _claim_log_html(claim: dict, events: list[dict], details: dict) -> str:
    rows = []
    for event in sorted(events, key=lambda e: e.get("occurred_at") or "", reverse=True):
        when = _fmt_date((event.get("occurred_at") or "")[:10])
        name = html.escape(str(event.get("trigger_name")))
        note = html.escape(str(event.get("note") or ""))
        rows.append(f"<tr><td style='padding:6px 12px 6px 0;white-space:nowrap'>{when}</td>"
                    f"<td style='padding:6px 12px;font-weight:bold'>{name}</td>"
                    f"<td style='padding:6px 0'>{note}</td></tr>")
    table = ("<table style='border-collapse:collapse;width:100%'>"
             + "".join(rows) + "</table>") if rows else "<p>No events recorded yet.</p>"
    loss = _fmt_date((claim.get("date_of_loss") or "")[:10], "[date of loss]")
    body = f"""
<p><strong>Claim log</strong> — peril: {html.escape(str(claim.get("peril") or "fire"))};
date of loss: {loss}.</p>
{table}
<p style="font-size:10pt;color:#555">Every entry is timestamped when recorded.
Add to this log every time anything happens on the claim.</p>
"""
    return _letter_html(body, details, "Claim log")


def _policy_request_html(details: dict) -> str:
    insurer = _d(details, "insurer_name", "[insurance company name]")
    claim_number = _d(details, "claim_number", "[claim number]")
    policy_number = _d(details, "policy_number", "[policy number]")
    body = f"""
<p><strong>Subject: Request for complete copy of policy</strong></p>
<p>To {insurer}:</p>
<p>Please send me a complete copy of my insurance policy — the declarations
page, the full policy form, and every endorsement — for policy number
{policy_number}, claim number {claim_number}.</p>
<p>I am requesting the complete policy in writing, not a summary. The
Homeowner Claims Bill of Rights (Fla. Stat. &sect; 627.7142) describes the
rights of Florida policyholders, and the full policy text is what controls
what is covered. Please send it to the address above or by email if that is
available.</p>
<p>Thank you.</p>
"""
    return _letter_html(body, details, "Policy request letter")


def _vacancy_notice_html(details: dict) -> str:
    insurer = _d(details, "insurer_name", "[insurance company name]")
    claim_number = _d(details, "claim_number", "[claim number]")
    policy_number = _d(details, "policy_number", "[policy number]")
    address = _d(details, "property_address", "[property address]")
    loss = _fmt_date((details or {}).get("date_of_loss"), "[date of loss]")
    body = f"""
<p><strong>Subject: Notice that the property is unoccupied</strong></p>
<p>To {insurer}:</p>
<p>This is written notice that the property at {address} has been unoccupied
since the covered loss on {loss}. Claim number {claim_number}, policy number
{policy_number}.</p>
<p>I am providing this notice in writing because many policies restrict
coverage on vacant homes after 30-60 days. Please confirm in writing that
this notice is on file for the claim.</p>
<p>Thank you.</p>
"""
    return _letter_html(body, details, "Vacancy notice")


def _work_auth_rider_html(details: dict) -> str:
    body = """
<p><strong>Rider to a repair or cleanup authorization</strong></p>
<p>Attach this rider to any repair or cleanup authorization before signing.
Write or type the specific terms into the blanks, then sign both the
authorization and this rider together.</p>
<p>1. Dollar cap: this authorization covers work up to $__________ total.
No work beyond that amount is authorized without a new written
authorization signed by the policyholder.</p>
<p>2. Scope: this authorization covers ONLY the following work:
____________________________________________________________</p>
<p>3. No assignment of insurance benefits: any clause assigning insurance
benefits under this agreement is stricken. For policies issued on or after
January 1, 2023, an assignment of benefits in a residential property
agreement is generally void under Fla. Stat. &sect; 627.7152, so it gives
nobody anything and only adds risk.</p>
<p>4. No disposal without consent: nothing may be disposed of or discarded
without the policyholder's written approval and a photograph of the item.</p>
"""
    return _letter_html(body, details, "Work authorization rider")


def _packout_demand_html(details: dict) -> str:
    insurer = _d(details, "insurer_name", "[insurance company name]")
    claim_number = _d(details, "claim_number", "[claim number]")
    body = f"""
<p><strong>Subject: Written item-level inventory before pack-out</strong></p>
<p>To {insurer}:</p>
<p>Before any pack-out crew loads a truck for claim number {claim_number}, I
am asking for the following in writing:</p>
<ul>
<li>An inventory of my belongings item by item — not box by box;</li>
<li>Photographs of the contents of each box as it is packed;</li>
<li>A written list of anything considered unsalvageable, agreed to before
anything is disposed of;</li>
<li>The storage location, my right of access, the daily storage rate, and
which coverage pays it — the contents limit or additional living
expenses.</li>
</ul>
<p>A box labeled only with a general description becomes the ceiling on what
that box's contents are worth. I am asking for the item-level list so the
record is complete from the start.</p>
<p>Thank you.</p>
"""
    return _letter_html(body, details, "Pack-out inventory demand")


_INVENTORY_COLUMNS = [
    "room", "item", "brand", "model", "serial", "qty", "age_years",
    "price_paid", "condition", "cost_new_today", "price_source",
]


def _contents_inventory_csv(details: dict) -> bytes:
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(_INVENTORY_COLUMNS)
    writer.writerow(["example: kitchen", "toaster", "Cuisinart", "CPT-122",
                     "12345XYZ", "1", "3", "45.00", "good", "59.99",
                     "amazon.com"])
    return buf.getvalue().encode("utf-8")


def _contents_inventory_html(details: dict) -> str:
    cols = "".join(f"<th style='padding:6px;border:1px solid #ccc'>{c}</th>" for c in _INVENTORY_COLUMNS)
    body = f"""
<p><strong>Contents inventory</strong></p>
<p>One row per item. Whoever writes the list controls what gets paid for it.
For proof when receipts burned: credit card and bank statements, email order
confirmations, online order history, warranty registrations, photos of the
home, social media, photos friends and family took, a prior mover's
inventory.</p>
<p style="font-size:10pt;color:#555">One hard rule: never list something you
did not own. Honest mistakes on a reconstructed list are normal; deliberate
padding is insurance fraud and can void the whole claim.</p>
<table style='border-collapse:collapse;width:100%;font-size:9pt'>
<tr>{cols}</tr>
<tr>{''.join(f"<td style='padding:6px;border:1px solid #ccc'>&nbsp;</td>" for _ in _INVENTORY_COLUMNS)}</tr>
</table>
"""
    return _letter_html(body, details, "Contents inventory")


def _depreciation_challenge_html(details: dict) -> str:
    insurer = _d(details, "insurer_name", "[insurance company name]")
    claim_number = _d(details, "claim_number", "[claim number]")
    body = f"""
<p><strong>Subject: Request for the depreciation schedule used</strong></p>
<p>To {insurer}:</p>
<p>For claim number {claim_number}, please provide the depreciation schedule
used to calculate the actual cash value payment, item by item, including the
age, condition, and depreciation percentage applied to each item.</p>
<p>I would like to review the schedule item by item. Some items depreciate
far less than a flat schedule assumes — antiques, art, jewelry, collectibles,
and light fixtures, for example. I will respond in writing with any items I
believe were depreciated incorrectly, with evidence.</p>
<p>Thank you.</p>
"""
    return _letter_html(body, details, "Depreciation challenge letter")


def _supplement_cover_html(details: dict) -> str:
    insurer = _d(details, "insurer_name", "[insurance company name]")
    claim_number = _d(details, "claim_number", "[claim number]")
    body = f"""
<p><strong>Subject: Supplemental claim — newly discovered damage</strong></p>
<p>To {insurer}:</p>
<p>Enclosed is a supplemental claim for damage discovered during demolition
that was not visible when the original scope was prepared.</p>
<p>Claim number {claim_number}. This is the routine way a claim's scope grows
during rebuilding; supplemental claims have their own reporting window under
Fla. Stat. &sect; 627.70132.</p>
<p>Attached: photographs, the contractor's description of the newly exposed
damage, and the repair estimate for the additional scope.</p>
<p>Thank you.</p>
"""
    return _letter_html(body, details, "Supplement cover letter")


def _demand_letter_html(details: dict) -> str:
    insurer = _d(details, "insurer_name", "[insurance company name]")
    claim_number = _d(details, "claim_number", "[claim number]")
    body = f"""
<p><strong>Subject: Written demand — line-item comparison</strong></p>
<p>To {insurer}:</p>
<p>This is a written demand for claim number {claim_number}. Below is the
line-item comparison between my independent estimate and the insurer's
estimate. Where the two differ, the attached documentation supports the
independent figure.</p>
<table style='border-collapse:collapse;width:100%;font-size:10pt'>
<tr><th style='border:1px solid #ccc;padding:6px'>Item</th>
<th style='border:1px solid #ccc;padding:6px'>Independent estimate</th>
<th style='border:1px solid #ccc;padding:6px'>Insurer estimate</th>
<th style='border:1px solid #ccc;padding:6px'>Evidence attached</th></tr>
<tr><td style='border:1px solid #ccc;padding:6px'>&nbsp;</td>
<td style='border:1px solid #ccc;padding:6px'>&nbsp;</td>
<td style='border:1px solid #ccc;padding:6px'>&nbsp;</td>
<td style='border:1px solid #ccc;padding:6px'>&nbsp;</td></tr>
</table>
<p>Please respond in writing. If the response does not resolve the
differences, the next steps in order are the free DFS consumer complaint
(1-877-MY-FL-CFO), DFS residential mediation under Fla. Stat. &sect;
627.7015, and appraisal if the policy still has that clause.</p>
<p>Thank you.</p>
"""
    return _letter_html(body, details, "Demand letter")


def _dfs_mediation_prefill_html(details: dict) -> str:
    insurer = _d(details, "insurer_name", "[insurance company name]")
    claim_number = _d(details, "claim_number", "[claim number]")
    policy_number = _d(details, "policy_number", "[policy number]")
    loss = _fmt_date((details or {}).get("date_of_loss"), "[date of loss]")
    body = f"""
<p><strong>DFS residential mediation request — information sheet</strong></p>
<p>This sheet gathers the information the Department of Financial Services
mediation request will ask for. Attach it to the current DFS mediation
request form, available from the Florida Department of Financial Services
website (myfloridacfo.com). Residential mediation is non-binding and
confidential, and the insurer pays for it (Fla. Stat. &sect; 627.7015).</p>
<p>Insured: {_d(details, "insured_name", "[your name]")}<br>
Property: {_d(details, "property_address", "[property address]")}<br>
Insurer: {insurer}<br>
Policy number: {policy_number}<br>
Claim number: {claim_number}<br>
Date of loss: {loss}<br>
Amount in dispute: $__________</p>
<p>Brief description of the disagreement (what the insurer's position is,
and what the policyholder's position is):</p>
<p style='min-height:3em'></p>
"""
    return _letter_html(body, details, "DFS mediation request prefill")


def _ics_escape(text: str) -> str:
    return (text.replace("\\", "\\\\").replace(";", "\\;")
            .replace(",", "\\,").replace("\n", "\\n"))


def _deadline_calendar_ics(claim: dict, deadlines: list[dict]) -> bytes:
    lines = ["BEGIN:VCALENDAR", "VERSION:2.0", "PRODID:-//LegalClear//Claim Deadlines//EN"]
    for i, dl in enumerate(deadlines):
        due = dl.get("due_date", "")
        if not due:
            continue
        uid = f"legalclear-{hash(str(claim.get('id')) + due + str(i)) & 0xFFFFFFFF:08x}"
        summary = _ics_escape(f"{dl.get('label', 'Deadline')} — {dl.get('governing_rule', '')}")
        lines += [
            "BEGIN:VEVENT",
            f"UID:{uid}@legalclear",
            f"DTSTAMP:{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}",
            f"DTSTART;VALUE=DATE:{due.replace('-', '')}",
            f"SUMMARY:{summary}",
            "END:VEVENT",
        ]
    lines.append("END:VCALENDAR")
    return ("\r\n".join(lines) + "\r\n").encode("utf-8")


# ────────────────────────────────────────────────────────────────────────
# Catalog + dispatch
# ────────────────────────────────────────────────────────────────────────

ARTIFACT_CATALOG: dict[str, dict] = {
    "claim_log": {"title": "Claim log", "batch": "A", "mime": "application/pdf", "ext": "pdf",
                  "phase": "all"},
    "policy_request_letter": {"title": "Written policy request letter", "batch": "A",
                              "mime": "application/pdf", "ext": "pdf", "phase": "fire.p1.first_week"},
    "vacancy_notice": {"title": "Vacancy notice to insurer", "batch": "A",
                       "mime": "application/pdf", "ext": "pdf", "phase": "fire.p1.first_week"},
    "work_auth_rider": {"title": "Scoped work authorization rider", "batch": "A",
                        "mime": "application/pdf", "ext": "pdf", "phase": "fire.p1.first_week"},
    "packout_demand": {"title": "Pack-out inventory demand letter", "batch": "A",
                       "mime": "application/pdf", "ext": "pdf", "phase": "fire.p3.contents_claim"},
    "contents_inventory_csv": {"title": "Contents inventory (CSV)", "batch": "A",
                               "mime": "text/csv", "ext": "csv", "phase": "fire.p3.contents_claim"},
    "contents_inventory_pdf": {"title": "Contents inventory (PDF form)", "batch": "A",
                               "mime": "application/pdf", "ext": "pdf", "phase": "fire.p3.contents_claim"},
    "depreciation_challenge": {"title": "Depreciation challenge letter", "batch": "B",
                               "mime": "application/pdf", "ext": "pdf", "phase": "fire.p4.the_money"},
    "supplement_cover": {"title": "Supplement submission cover letter", "batch": "B",
                         "mime": "application/pdf", "ext": "pdf", "phase": "fire.p5.rebuilding"},
    "demand_letter": {"title": "Demand letter with line-item delta", "batch": "B",
                      "mime": "application/pdf", "ext": "pdf", "phase": "fire.p6.dispute_ladder"},
    "dfs_mediation_prefill": {"title": "DFS mediation request prefill", "batch": "B",
                              "mime": "application/pdf", "ext": "pdf", "phase": "fire.p6.dispute_ladder"},
    "deadline_calendar_ics": {"title": "Deadline calendar (.ics)", "batch": "B",
                              "mime": "text/calendar", "ext": "ics", "phase": "all"},
}


def build_artifact(
    artifact_id: str,
    claim: dict,
    events: list[dict],
    deadlines: list[dict],
    details: dict,
) -> tuple[bytes, str, str]:
    """Return (bytes, mime, filename) for one artifact.

    Raises KeyError for an unknown artifact_id (the router maps that to 404).
    """
    meta = ARTIFACT_CATALOG[artifact_id]
    filename = f"{artifact_id}_{datetime.now(timezone.utc).strftime('%Y%m%d')}.{meta['ext']}"

    if artifact_id == "claim_log":
        return _render_pdf(_claim_log_html(claim, events, details)), meta["mime"], filename
    if artifact_id == "policy_request_letter":
        return _render_pdf(_policy_request_html(details)), meta["mime"], filename
    if artifact_id == "vacancy_notice":
        return _render_pdf(_vacancy_notice_html(details)), meta["mime"], filename
    if artifact_id == "work_auth_rider":
        return _render_pdf(_work_auth_rider_html(details)), meta["mime"], filename
    if artifact_id == "packout_demand":
        return _render_pdf(_packout_demand_html(details)), meta["mime"], filename
    if artifact_id == "contents_inventory_csv":
        return _contents_inventory_csv(details), meta["mime"], filename
    if artifact_id == "contents_inventory_pdf":
        return _render_pdf(_contents_inventory_html(details)), meta["mime"], filename
    if artifact_id == "depreciation_challenge":
        return _render_pdf(_depreciation_challenge_html(details)), meta["mime"], filename
    if artifact_id == "supplement_cover":
        return _render_pdf(_supplement_cover_html(details)), meta["mime"], filename
    if artifact_id == "demand_letter":
        return _render_pdf(_demand_letter_html(details)), meta["mime"], filename
    if artifact_id == "dfs_mediation_prefill":
        return _render_pdf(_dfs_mediation_prefill_html(details)), meta["mime"], filename
    if artifact_id == "deadline_calendar_ics":
        return _deadline_calendar_ics(claim, deadlines), meta["mime"], filename
    raise KeyError(artifact_id)
