#!/usr/bin/env python3
"""Generate the mechanical fields of STATUS.md.

Derives, fresh each run:
  - current SHA (must equal origin/main)
  - prod row counts (statutes, court_rules, court_forms, legal_opinions)
  - educational checker baseline
  - test suite count

Writes the mechanical block into STATUS.md between the markers
`<!-- GEN:START -->` and `<!-- GEN:END -->`. Prose fields between the
`<!-- PROSE:START -->` and `<!-- PROSE:END -->` markers are untouched —
those are written by the session runner, never by this script.

Usage: python3 scripts/gen_status.py [--skip-suite]
"""
import datetime
import json
import os
import re
import subprocess
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
STATUS = ROOT / "STATUS.md"
ENV = ROOT / "backend" / ".env"


def load_env() -> dict[str, str]:
    env: dict[str, str] = {}
    if ENV.exists():
        for line in ENV.read_text().splitlines():
            if "=" in line and not line.startswith("#"):
                k, _, v = line.partition("=")
                env.setdefault(k.strip(), v.strip())
    return env


def git(*args: str) -> str:
    return subprocess.run(
        ["git", *args], cwd=ROOT, capture_output=True, text=True, check=True
    ).stdout.strip()


def sha_check() -> dict[str, str]:
    local = git("rev-parse", "HEAD")
    try:
        git("fetch", "origin", "--quiet")
    except subprocess.CalledProcessError:
        pass
    origin = git("rev-parse", "origin/main")
    short = git("rev-parse", "--short", "HEAD")
    return {
        "sha": local,
        "short": short,
        "origin_main": origin,
        "in_sync": "YES" if local == origin else "NO — PUSH PENDING",
    }


def prod_counts() -> dict[str, int]:
    env = load_env()
    url = env.get("SUPABASE_URL", "").rstrip("/")
    key = env.get("SUPABASE_SERVICE_KEY", "")
    if not url or not key:
        return {"statutes": -1, "court_rules": -1, "court_forms": -1, "legal_opinions": -1}
    hdr = {"apikey": key, "Authorization": f"Bearer {key}"}
    out: dict[str, int] = {}
    for table in ("statutes", "court_rules", "court_forms"):
        req = urllib.request.Request(f"{url}/rest/v1/{table}?select=count", headers=hdr)
        try:
            body = json.loads(urllib.request.urlopen(req, timeout=60).read().decode())
            out[table] = body[0]["count"]
        except Exception:  # noqa: BLE001
            out[table] = -1
    req = urllib.request.Request(
        f"{url}/rest/v1/legal_opinions?select=id&limit=1",
        headers={**hdr, "Prefer": "count=estimated"},
    )
    try:
        resp = urllib.request.urlopen(req, timeout=90)
        out["legal_opinions"] = int(resp.headers.get("content-range", "0-0/0").split("/")[-1])
    except Exception:  # noqa: BLE001
        out["legal_opinions"] = -1
    return out


def checker_baseline() -> str:
    env = dict(os.environ)
    env.pop("PYTHONPATH", None)
    try:
        r = subprocess.run(
            [sys.executable, "scripts/verify_educational.py"],
            cwd=ROOT, capture_output=True, text=True, timeout=300, env=env,
        )
        m = re.search(r"BASELINE: (\d+) violation\(s\) across (\d+) checks", r.stdout)
        if m:
            return f"{m.group(1)} violations across {m.group(2)} checks"
        return f"checker ran (exit {r.returncode}); baseline line not parsed"
    except subprocess.TimeoutExpired:
        return "checker timed out"


def suite_count() -> str:
    env = dict(os.environ)
    try:
        r = subprocess.run(
            [sys.executable, "-m", "pytest", "tests/", "--collect-only", "-q"],
            cwd=ROOT / "backend", capture_output=True, text=True, timeout=300, env=env,
        )
        m = re.search(r"(\d+) tests collected", r.stdout)
        if m:
            return f"{m.group(1)} tests collected"
        return "suite collect failed"
    except subprocess.TimeoutExpired:
        return "suite collect timed out"


def main() -> None:
    skip_suite = "--skip-suite" in sys.argv
    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    s = sha_check()
    c = prod_counts()
    cb = checker_baseline()
    sc = suite_count() if not skip_suite else "skipped (--skip-suite)"

    block = f"""<!-- GEN:START — DO NOT EDIT — generated by scripts/gen_status.py -->
generated: {now}
sha: {s['short']} ({s['sha']})
origin_main: {s['origin_main']}
sync: {s['in_sync']}
prod_counts: statutes={c['statutes']} court_rules={c['court_rules']} court_forms={c['court_forms']} legal_opinions={c['legal_opinions']}
checker: {cb}
suite: {sc}
<!-- GEN:END -->"""

    if STATUS.exists():
        text = STATUS.read_text()
        if "<!-- GEN:START -->" in text:
            text = re.sub(
                r"<!-- GEN:START -->.*?<!-- GEN:END -->",
                block, text, flags=re.DOTALL,
            )
        else:
            text += "\n" + block
    else:
        text = f"""# STATUS.md — ledger of last record

Any report whose sha, prod_counts, or checker disagree with this file is STALE by
definition. Regenerate at the end of every work session:
`python3 scripts/gen_status.py`, then write the prose fields by hand.

{block}

## Prose — written by the session runner

<!-- PROSE:START -->

<!-- PROSE:END -->
"""
    STATUS.write_text(text)
    print(f"STATUS.md updated: {s['short']} sync={s['in_sync']} "
          f"statutes={c['statutes']} rules={c['court_rules']} forms={c['court_forms']} "
          f"opinions={c['legal_opinions']} checker={cb} suite={sc}")


if __name__ == "__main__":
    main()
