-- Phase 2: seed court_forms with the FL family law catalog.
-- 12 verified forms (content_id + source_download_url confirmed from flcourts.gov).
-- 39 form-group catalog entries (pending_harvest — no download URL yet).
-- All start with status='unverified'; set to 'active' via harvest_form.py
-- after a human downloads and uploads each PDF to the court-forms bucket.

insert into public.court_forms
  (form_number, title, category, court_revision_date, content_id,
   source_download_url, source_page_url, situation_tags, status)
values

-- ── Verified individual forms ────────────────────────────────────────────────
('12.901(a)',
 'Joint Petition for Simplified Dissolution of Marriage',
 'family_law', '06/2025', '685807',
 'https://www.flcourts.gov/content/download/685807/file_pdf/901a.pdf',
 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/',
 array['divorce','simplified_dissolution','agreed','no_children'],
 'unverified'),

('12.901(b)(1)',
 'Petition for Dissolution of Marriage with Dependent or Minor Child(ren)',
 'family_law', '02/2018', '685808',
 'https://www.flcourts.gov/content/download/685808/file_pdf/901b1.pdf',
 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/',
 array['divorce','dissolution_with_children','minor_children'],
 'unverified'),

('12.901(b)(2)',
 'Petition for Dissolution of Marriage with Property but No Dependent or Minor Child(ren)',
 'family_law', '02/2018', '685809',
 'https://www.flcourts.gov/content/download/685809/file_pdf/901b2.pdf',
 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/',
 array['divorce','dissolution_with_property','no_children'],
 'unverified'),

('12.901(b)(3)',
 'Petition for Dissolution of Marriage with No Dependent or Minor Child(ren) or Property',
 'family_law', '02/2018', '685810',
 'https://www.flcourts.gov/content/download/685810/file_pdf/901b3.pdf',
 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/',
 array['divorce','dissolution_no_property','no_children'],
 'unverified'),

('12.902(c)',
 'Family Law Financial Affidavit (Long Form)',
 'family_law', '06/2025', '685813',
 'https://www.flcourts.gov/content/download/685813/file_pdf/12.902c.pdf',
 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/',
 array['divorce','financial_affidavit','high_income'],
 'unverified'),

('12.902(d)',
 'Uniform Child Custody Jurisdiction and Enforcement Act (UCCJEA) Affidavit',
 'family_law', null, '685814',
 'https://www.flcourts.gov/content/download/685814/file_pdf/902d.pdf',
 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/',
 array['divorce','custody','uccjea','jurisdiction'],
 'unverified'),

('12.902(e)',
 'Child Support Guidelines Worksheet',
 'family_law', '06/2025', '685815',
 'https://www.flcourts.gov/content/download/685815/file_pdf/12.902e.pdf',
 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/',
 array['divorce','child_support','guidelines_worksheet'],
 'unverified'),

('12.902(f)(1)',
 'Marital Settlement Agreement for Dissolution of Marriage with Dependent or Minor Child(ren)',
 'family_law', '02/2018', '685816',
 'https://www.flcourts.gov/content/download/685816/file_pdf/902f1.pdf',
 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/',
 array['divorce','settlement_agreement','children'],
 'unverified'),

('12.903(b)',
 'Answer to Petition for Dissolution of Marriage',
 'family_law', null, '685823',
 'https://www.flcourts.gov/content/download/685823/file_pdf/903b.pdf',
 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/',
 array['divorce','answer','responding'],
 'unverified'),

('12.903(c)(1)',
 'Answer to Petition and Counterpetition for Dissolution of Marriage with Dependent or Minor Child(ren)',
 'family_law', '02/2018', '685824',
 'https://www.flcourts.gov/content/download/685824/file_pdf/903c1.pdf',
 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/',
 array['divorce','answer','counterpetition','children'],
 'unverified'),

('12.905(a)',
 'Supplemental Petition to Modify Parental Responsibility / Time-Sharing and Other Relief',
 'family_law', '11/2015', '685834',
 'https://www.flcourts.gov/content/download/685834/file_pdf/905a.pdf',
 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/',
 array['custody','modification','time_sharing','parental_responsibility'],
 'unverified'),

('12.910(a)',
 'Summons: Personal Service on an Individual',
 'family_law', null, '685838',
 'https://www.flcourts.gov/content/download/685838/file_pdf/910a.pdf',
 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/',
 array['summons','service','personal_service'],
 'unverified'),

-- ── Form-group catalog entries (pending harvest) ─────────────────────────────
('12.900',  'Attorney / Non-Lawyer Representation (Forms A-H)',               'family_law', null, null, null, 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/', null, 'unverified'),
('12.901',  'Petition for Dissolution of Marriage (Forms A-B3)',               'family_law', null, null, null, 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/', null, 'unverified'),
('12.902',  'Additional Supporting Documents (Forms B-J)',                     'family_law', null, null, null, 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/', null, 'unverified'),
('12.903',  'Answers to Dissolution (Forms A-E)',                              'family_law', null, null, null, 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/', null, 'unverified'),
('12.912',  'Military Service (Forms A-B)',                                    'family_law', null, null, null, 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/', null, 'unverified'),
('12.913',  'Notices and Diligent Search (Forms A-C)',                         'family_law', null, null, null, 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/', null, 'unverified'),
('12.914',  'Certificate of Service (General)',                                'family_law', null, null, null, 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/', null, 'unverified'),
('12.915',  'Designation of Current Mailing and E-mail Address',               'family_law', null, null, null, 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/', null, 'unverified'),
('12.920',  'Form Group 12.920 (Forms A-C)',                                   'family_law', null, null, null, 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/', null, 'unverified'),
('12.921',  'Form Group 12.921',                                               'family_law', null, null, null, 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/', null, 'unverified'),
('12.922',  'Motion for Default (Forms A-C)',                                  'family_law', null, null, null, 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/', null, 'unverified'),
('12.923',  'Notice of Hearing (General)',                                     'family_law', null, null, null, 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/', null, 'unverified'),
('12.924',  'Notice for Trial',                                                'family_law', null, null, null, 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/', null, 'unverified'),
('12.927',  'Form Group 12.927',                                               'family_law', null, null, null, 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/', null, 'unverified'),
('12.928',  'Form Group 12.928',                                               'family_law', null, null, null, 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/', null, 'unverified'),
('12.930',  'Discovery (Forms A-D)',                                           'family_law', null, null, null, 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/', null, 'unverified'),
('12.931',  'Form Group 12.931 (Forms A-B)',                                   'family_law', null, null, null, 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/', null, 'unverified'),
('12.932',  'Certificate of Compliance with Mandatory Disclosure',             'family_law', null, null, null, 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/', null, 'unverified'),
('12.940',  'Dissolve / Modify Injunction (Forms D-E)',                        'family_law', null, null, null, 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/', null, 'unverified'),
('12.942',  'Guardian ad Litem (Forms A-B)',                                   'family_law', null, null, null, 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/', null, 'unverified'),
('12.943',  'Motion to Deviate from Child Support Guidelines',                 'family_law', null, null, null, 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/', null, 'unverified'),
('12.950',  'Involving Relocation (Forms A-J)',                                'family_law', null, null, null, 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/', null, 'unverified'),
('12.951',  'Disestablish Paternity (Forms A-B)',                              'family_law', null, null, null, 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/', null, 'unverified'),
('12.960',  'Enforcement',                                                     'family_law', null, null, null, 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/', null, 'unverified'),
('12.961',  'Form Group 12.961',                                               'family_law', null, null, null, 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/', null, 'unverified'),
('12.970',  'Form Group 12.970 (Forms A-F)',                                   'family_law', null, null, null, 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/', null, 'unverified'),
('12.975',  'Form Group 12.975 (Forms A-B)',                                   'family_law', null, null, null, 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/', null, 'unverified'),
('12.980',  'Domestic Violence and Dating Violence (Forms A-E, N-P)',          'family_law', null, null, null, 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/', null, 'unverified'),
('12.981',  'Adoption (Forms A1-D2)',                                          'family_law', null, null, null, 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/', null, 'unverified'),
('12.982',  'Name Change (Forms A-G)',                                         'family_law', null, null, null, 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/', null, 'unverified'),
('12.983',  'Paternity (Forms A-G)',                                           'family_law', null, null, null, 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/', null, 'unverified'),
('12.984',  'Form Group 12.984 (Forms A-D)',                                   'family_law', null, null, null, 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/', null, 'unverified'),
('12.985',  'Form Group 12.985 (Forms A-G)',                                   'family_law', null, null, null, 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/', null, 'unverified'),
('12.990',  'Dissolution Final Judgments (Forms A-C2)',                        'family_law', null, null, null, 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/', null, 'unverified'),
('12.993',  'Modification of Final Judgments (Forms A-C)',                     'family_law', null, null, null, 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/', null, 'unverified'),
('12.994',  'Form Group 12.994 (Forms A-B)',                                   'family_law', null, null, null, 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/', null, 'unverified'),
('12.995',  'Parenting Plan (Forms A-C)',                                      'family_law', null, null, null, 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/', null, 'unverified'),
('12.996',  'Income Deduction Order (Forms A-C)',                              'family_law', null, null, null, 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/', null, 'unverified'),
('12.999',  'Disposition / Cover Sheet',                                       'family_law', null, null, null, 'https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Law-Forms/', null, 'unverified')

on conflict (form_number) do nothing;
